"""add technologies to projects

Revision ID: d9a2cc141e6a
Revises: f87dbe6a3890
Create Date: 2026-08-01 01:25:03.417386

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9a2cc141e6a"
down_revision: str | Sequence[str] | None = "f87dbe6a3890"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("technologies", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "technologies")
    # ### end Alembic commands ###
