"""add website url to projects

Revision ID: f87dbe6a3890
Revises: 7b11003d2c3a
Create Date: 2026-07-22 23:20:38.136008

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f87dbe6a3890"
down_revision: str | Sequence[str] | None = "7b11003d2c3a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("website_url", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "website_url")
    # ### end Alembic commands ###
